CREATE TABLE fixed_winners_settings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  game_name VARCHAR(255) NOT NULL,
  fixed_clan VARCHAR(100) DEFAULT NULL,
  enabled BOOLEAN DEFAULT FALSE,
  total_match INT DEFAULT 0,
  completed_match INT DEFAULT 0,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
