//
NODE_ENV= 
PORT=

// to run matc cycle 
MATCH_FULL_TIME=
MATCH_BET_COUNTDOWN=
COUNTDOWN_INTERVAL=
MATCH_GAP=


// to create random dummy users count and bet amount
INTERVALMS =  //in ms 
MINBETINCREASE =
MAXBETINCREASE =
MINCOUNTINCREASE =
MAXCOUNTINCREASE 


//DB CONFIGURATION
DB_HOST = 
DB_USERNAME = root
DB_PASSWORD = 
DB_NAME  = socketservice
DB_PORT  = 3306
 